### ISSUE TITLE
Error when running lmercens

### ISSUE THREAD

**Issue by drputri** [lenz99-/lme4cens#3]
Hi there,

I found your package from useR! 2017 poster. I'm able to install the package. I downloaded the whole folder from your github and try to run this _example_lmm_cens.Rmd_ file on my local drive. However, when I run this line code:
```
fm.lmercens <- lmercens(Surv(Reaction3, time2 = Reaction3, event = event3, type = "interval") ~ Days + (1|Subject),
                        data = sleepstudy2, REML = FALSE,
                        control = lmerControl(optimizer = "optimx", optCtrl = list(method = "L-BFGS-B"), boundary.tol = 0),
                        start = paramSL)
```
 
I got the error saying as follow
```
 Error in optimx.check(par, optcfg$ufn, optcfg$ugr, optcfg$uhess, lower,  : 
  Cannot evaluate function at initial parameters
```

Could you please help me to identify what goes wrong here? I run as well the paramSL where you defined your starting values.
Thank you beforehand.

Dea

**Comment by lenz99-** [comment]
Hallo Dea,

Thanks for your interest in my package lme4cens.
To me it looks like as if you have not loaded the lme4cens package in this session? Because the object ghQuadRule lives within the package and should be available once the package is loaded, e.g. via a call to library().

On GitHub I have seen that you also have raised an issue where you have updated the error message. This I can not reproduce. It looks like as if the start values are not good. Please try to run lmercens() directly on the start-values, i.e. without optimisation. I post on the Github issue so it is visible for everyone.

Thanks again
And good luck


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Matthias Kuhn
Wissenschaftlicher Mitarbeiter

Institut für medizinische Informatik und Biometrie (IMB)
Medizinische Fakultät der TU Dresden
Zimmer 3.403, Haus 105, Blasewitzer Str 86

Tel:  +49(0)351 458-6057
Fax: +49(0)351 458-7222
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by drputri** [comment]
Hi Matthias, 

Thank you so much for your quick response. I updated with the last version from GitHub and re-run the vignettes of the markdown, now everything runs perfectly. Plus when I was using the older version, I couldn't get the summary of the fixed effects, but using the current version, I can get the summary of the fixed effects.

I also run your code on my internal data and compared the result with the result from SAS and both of them are comparable. 
Really nice to be be able to run this in R now :) Many many thanks.. 


Cheers,
Dea
